/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 22:32:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class course_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("      body {\r\n");
      out.write("        padding-top: 40px;\r\n");
      out.write("        padding-bottom: 40px;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-signin {\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        padding: 19px 29px 29px;\r\n");
      out.write("        margin: 0 auto 20px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #e5e5e5;\r\n");
      out.write("        -webkit-border-radius: 5px;\r\n");
      out.write("           -moz-border-radius: 5px;\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("                box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin .form-signin-heading,\r\n");
      out.write("      .form-signin .checkbox {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin input[type=\"text\"],\r\n");
      out.write("      .form-signin input[type=\"password\"] {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        padding: 7px 9px;\r\n");
      out.write("      }\r\n");
      out.write("\t\r\n");
      out.write("    </style>\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container form-signin\">\r\n");
      out.write(" <div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("<h3 class=\"form-signin-heading text-warning\">查看选了某个课程的用户数量</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href =\"course_manage.jsp?action=yes_choose\">打开选课开关</a>\r\n");
      out.write("<a href =\"course_manage.jsp?action=no_choose\">关闭选课开关</a>\r\n");
      out.write("\r\n");

	String this_url = "course_manage.jsp"; 	
	JdbcDao jdbc = new JdbcDao();
	
	String action = request.getParameter("action");
	System.out.println(action);
	if(action != null)//删除某个课程
	{
		System.out.println("In action");
		if(action.equals("delete"))
		{
			int course_id = Integer.parseInt(request.getParameter("id"));
			try{
				jdbc.delCourse(course_id);
				System.out.println("Delete course: ID= "+course_id);
				response.sendRedirect(this_url);
			}
			catch(Exception e)
			{
				System.out.println(e);
			}
		}
		else if(action.equals("yes_choose"))
		{
			Status s = jdbc.getStatus();
			s.choose = 1;
			jdbc.updateStatus(s);
			response.sendRedirect(this_url);
		}
		else if(action.equals("no_choose"))
		{
			Status s = jdbc.getStatus();
			s.choose = 0;
			jdbc.updateStatus(s);
			response.sendRedirect(this_url);
		}	
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <table class=\"table table-striped text-center\">\r\n");
      out.write("\r\n");
	
	List<Integer> c= jdbc.getCourseIndex(0);
	int cnt = 0;
	if(c!=null){
		for(Integer i : c)
		{ 
			++cnt;
			Course course = jdbc.getCourse(i);
			String info_url = "../courses/course.jsp?id="+course.id+"&type=1";
			String delete_url = this_url+"?id="+course.id+"&action=delete";
			String edit_url = "course_edit.jsp?id="+course.id;
			String user_url = "course_user.jsp?id="+course.id;
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(cnt);
      out.write(". </td>\r\n");
      out.write("\t\t\t<td><a href= ");
      out.print(info_url);
      out.write('>');
      out.print(course.name);
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td><a href= ");
      out.print(edit_url);
      out.write(">编辑修改课程</a></td>\r\n");
      out.write("\t\t\t<td><a href= ");
      out.print(delete_url);
      out.write(">删除</a></td>\r\n");
      out.write("\t\t\t<td><a href= ");
      out.print(user_url);
      out.write(">查看选课学生</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

		} 
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write(" <table class=\"table table-striped text-center\">\r\n");
      out.write("<hr><form name=\"发布新课程\"action=");
      out.print(this_url);
      out.write(" method=\"post\">\r\n");
      out.write("\t<p class=\"text-info\">添加课程界面：</p>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>课程名称</td><td><input type=\"text\" name=\"name\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>授课老师</td><td><input type=\"text\" name=\"teacher\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>上课时间</td><td><input type=\"text\" name=\"classtime\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>课容量</td><td><input type=\"text\" name=\"capacity\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>课程介绍</td><td><input type=\"text\" name=\"content\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type=\"submit\" class=\"btn btn-primary\" name=\"add_confirm\" value=\"确认\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>\r\n");

	if(request.getParameter("add_confirm")!=null)//发布新课程
	{
		//<br/>课程开始时间<input type="text" name="start_time" /> <br/>课程结束时间<input type="text" name="end_time" />
	
		System.out.println("in add_confirm");
		try {
			
			Course tmp = new Course();
			tmp.name = request.getParameter("name");
			tmp.teacher = request.getParameter("teacher");

			tmp.classtime = request.getParameter("classtime");
			
			if(request.getParameter("capacity")!=null && !request.getParameter("capacity").equals(""))
				tmp.capacity = Integer.parseInt(request.getParameter("capacity"));
			
			tmp.valid = 1;

			tmp.content = request.getParameter("content");
			tmp.start_time = request.getParameter("start_time");
			tmp.end_time = request.getParameter("end_time");
			
			
			int validation = tmp.isValid();
			if(validation == 0)
			{
				
      out.write("<p class=\"text-error\">课程信息没有补全</p>");

			}
			else if(validation == -1)
			{
				
      out.write("<p class=\"text-error\">上课信息不合法</p>");

			}
			else if(validation == 1)
			{
				int course_id = jdbc.addCourse(tmp);
				System.out.println("加入课程ID！"+course_id);				
				response.sendRedirect("../courses/course.jsp?id="+course_id);
			}
		} catch (Exception e) {
			System.out.println(e);
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<hr><a href=\"../home.jsp\">返回首页</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
