/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-20 15:26:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class discussion_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>该界面提供新开一个分类，可以点开进去看</h1>\r\n");
      out.write("\r\n");

	User user_ = (User)session.getAttribute("user");

      out.write("\r\n");
      out.write("\r\n");
  
	JdbcDao jdbc = new JdbcDao();
	List<Integer> c=null;
	c = jdbc.getCategoryIndex();
	int cnt = 0;

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<font size = 6 face =\"微软雅黑\" >\r\n");
      out.write("<p><b>讨论区的版块如下</b></p>\r\n");
      out.write("</font>\r\n");
      out.write("\r\n");
      out.write("<font size = 4 face =\"微软雅黑\" >\r\n");
      out.write("<ul>\r\n");
 
	if(c!=null){
		for(Integer i: c)
		{ 
			Category category = jdbc.getCategory(i);
			String post_url = "posts.jsp?category_id="+category.id;
			++cnt;
			
      out.write("<li><b>");
      out.print(cnt);
      out.write(". <a href= ");
      out.print(post_url );
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print(category.name);
      out.write(" </a></b></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
		
		} 
	}

      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("<hr><br><a href=\"../home.jsp\">返回首页</a>\r\n");
      out.write("<hr>");
 
	if(user_ != null){
	
      out.write("\r\n");
      out.write("<font size = 3 face =\"微软雅黑\" color=\"#00FFFF\">\r\n");
      out.write("\t你的名字：");
      out.print(user_.realname );
      out.write("<br>\r\n");
      out.write("\t你的ID：");
      out.print(user_.id );
      out.write("<br>\r\n");
      out.write("\t你的地址：");
      out.print(user_.address );
      out.write("<br>\r\n");
      out.write("</font>\r\n");
 	}
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
