/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 22:27:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class media_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("      body {\r\n");
      out.write("        padding-top: 40px;\r\n");
      out.write("        padding-bottom: 40px;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-signin {\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        padding: 19px 29px 29px;\r\n");
      out.write("        margin: 0 auto 20px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #e5e5e5;\r\n");
      out.write("        -webkit-border-radius: 5px;\r\n");
      out.write("           -moz-border-radius: 5px;\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("                box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin .form-signin-heading,\r\n");
      out.write("      .form-signin .checkbox {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin input[type=\"text\"],\r\n");
      out.write("      .form-signin input[type=\"password\"] {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        padding: 7px 9px;\r\n");
      out.write("      }\r\n");
      out.write("\t\r\n");
      out.write("    </style>\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container form-signin\">\r\n");
      out.write(" <div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h4>资源列表</h4>\r\n");

	String this_url = "media_manage.jsp"; 	
	JdbcDao jdbc = new JdbcDao();
	String action = request.getParameter("action");
	System.out.println(action);
	if(action != null)//删除某个课程
	{
		if(action.equals("delete"))
		{
			String id_string = request.getParameter("id");
			if(id_string != null)
			{
				int media_id = Integer.parseInt(id_string);
				jdbc.delMedia(media_id);
				System.out.println("delete the media");
			}
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
	
	List<Integer> c= jdbc.getMediaIndex(0);
	int cnt = 0;
	if(c!=null){
		
      out.write("<table>");

		for(Integer i : c)
		{ 
			++cnt;
			Media media = jdbc.getMedia(i);
			String show_url= "../media/show.jsp?id="+media.id;
			String del_url = this_url+"?action=delete&id="+media.id;
			
      out.write("<tr><td>");
      out.print(media.content);
      out.write("</td>");
		
			
      out.write("<td>");
      out.print(media.url);
      out.write("</td>");

			
      out.write("<td>");
      out.print(media.type);
      out.write("</td>");

			
      out.write("<td><a href=\"");
      out.print(show_url);
      out.write("\">查看</a></td>");

			
      out.write("<td><a href=\"");
      out.print(del_url);
      out.write("\">删除</a></td></tr>");

		}
		
      out.write("</table>");

	}

      out.write("\r\n");
      out.write(" <table class=\"table table-striped text-center\">\r\n");
      out.write("<hr><form name=\"添加外部资源\"action=");
      out.print(this_url);
      out.write(" method=\"post\">\r\n");
      out.write("\t<p class=\"text-info\">添加资源界面：</p>\r\n");
      out.write("\t<tr><td>资源类型</td><td><input type=\"text\" name=\"type\" /></td></tr>\r\n");
      out.write("\t<tr><td>资源链接</td><td><input type=\"text\" name=\"url\" /></td></tr>\r\n");
      out.write("\t<tr><td>资源名称</td><td><input type=\"text\" name=\"name\" /></td></tr>\r\n");
      out.write("\t<tr><td>资源描述</td><td><input type=\"text\" name=\"content\" /></td></tr>\r\n");
      out.write("\t<tr><td><input type=\"submit\" name=\"add_confirm\" value=\"确认\" /></td></tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

	if(request.getParameter("add_confirm")!=null)//发布新课程
	{
		System.out.println("in add_confirm");
		try {
			Media m = new Media();
			String type = request.getParameter("type");
			if(type!=null)
				m.type = Integer.parseInt(type);
			m.name = request.getParameter("name");
			m.url = request.getParameter("url");
			m.content = request.getParameter("content");
			if(m.isValid())
			{
				jdbc.addMedia(m);
				System.out.println("加入mediaID！");				
				response.sendRedirect(this_url);
			}
			else{	
				
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"text-error\">请补全所有信息，并注意type的表示（1：图片  2：音频  3：视频）</p>\r\n");
      out.write("\t\t\t\t");

			}
		} catch (Exception e) {
			System.out.println(e);
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<hr><a href=\"../home.jsp\">返回首页</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
