/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 22:27:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class user_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3 class=\"text-success\">用户权限管理</h3>\r\n");
      out.write("\r\n");

	String this_url = "user_manage.jsp"; 	
	JdbcDao jdbc = new JdbcDao();
	List<Integer> c= jdbc.getUserIndex();
	String action = null;
	action = request.getParameter("action");
	if(action != null)
	{
		User user = new User(); 
		user.id = Integer.parseInt(request.getParameter("id"));
		user = jdbc.getUser(user);
		if(action.equals("not_login"))
			user.permit_login = 0;
		else if(action.equals("yes_login"))
			user.permit_login = 1;
		else if(action.equals("not_post"))
			user.permit_post = 0;
		else if(action.equals("yes_post"))
			user.permit_post = 1;
		else if(action.equals("yes_admin"))
			user.permit_admin = 1;
		else if(action.equals("not_admin"))
			user.permit_admin = 0;
		jdbc.updateUser(user);
		response.sendRedirect(this_url);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<table class=\"table table-striped text-center\">\r\n");
	
	int cnt = 0;
	if(c!=null){
		for(Integer i : c)
		{ 
			++cnt;
			User tmp = new User(); tmp.id = i;
			User user = jdbc.getUser(tmp);
			 
			String not_login = this_url+"?id="+user.id+"&action=not_login";
			String yes_login = this_url+"?id="+user.id+"&action=yes_login";
			String not_post = this_url+"?id="+user.id+"&action=not_post";
			String yes_post = this_url+"?id="+user.id+"&action=yes_post";
			String not_admin = this_url+"?id="+user.id+"&action=not_admin";
			String yes_admin = this_url+"?id="+user.id+"&action=yes_admin";
			
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(cnt);
      out.write('.');
      out.print(user.account);
      out.write('|');
      out.print(user.nickname);
      out.write("|</td>\r\n");
      out.write("\t\t\t<td>登录权限");
      out.print(user.permit_login);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>发帖权限");
      out.print(user.permit_post);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>管理员权限");
      out.print(user.permit_admin);
      out.write("</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(not_login);
      out.write(">禁止登陆</a></td>  \r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(yes_login);
      out.write(">恢复登陆</a></td>\r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(not_post );
      out.write(">禁止发帖 </a></td>\r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(yes_post );
      out.write(">恢复发帖</a></td>\r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(yes_admin );
      out.write(">升级为管理员 </a></td>\r\n");
      out.write("\t\t\t<td><a href = ");
      out.print(not_admin );
      out.write(">取消管理员 </a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

		} 
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr><a href=\"../home.jsp\" style=\"color:green\">返回首页</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
