/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 08:29:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class choose_005fnew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("h1 {color:#00ff00}\n");
      out.write("p.ex {color:rgb(0,0,255)}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");

	JdbcDao jdbc = new JdbcDao();
	Status s = jdbc.getStatus();
	if(s.choose == 0)
	{
		
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-error\">\n");
      out.write("  \t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t <strong>Warning!</strong> 选课开关没有打开，现在不是选课时间\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t");
 
		return;
	}

      out.write('\n');
      out.write('\n');

	User user = (User)session.getAttribute("user");
	if(user != null){
	
      out.write("\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("  \t<div class=\"row-fluid\">\n");
      out.write("    <div class=\"span3\">\n");
      out.write("    <font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的名字：");
      out.print(user.realname );
      out.write("<br></p></font>\n");
      out.write("\t<font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的ID：");
      out.print(user.id );
      out.write("<br></p></font>\n");
      out.write("\t<font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的地址：");
      out.print(user.address );
      out.write("<br></p></font>\n");
 	}
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"span9\">\n");
      out.write("      <font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>可选课程</b></p></font>\n");
  
	List<Integer> c=null; 
	user = (User)session.getAttribute("user");
	if(user==null)
	{
		
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-error\">\n");
      out.write("  \t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t <strong>Warning!</strong> 你还没有登陆，所以没有课程可以选择\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 
		return;
	}
	else
		c = jdbc.getCourseIndex(0);
	int cnt = 0;

      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("<table class=\"table table-striped\">\n");
 
	if(c!=null){
		for(Integer i : c)
		{
			System.out.println(request.getRemoteAddr().toString());
			Course course = jdbc.getCourse(i);
			String info_url = "course.jsp?id="+course.id+"&type=1";
			String in_url = "getin.jsp?cid="+course.id+"&uid="+user.id;
			
			int ans = jdbc.checkUserCourse(user.id, course.id);
			int chosen = course.capacity - jdbc.getUserCourse(course.id).size();
			++cnt;
			
      out.write("\n");
      out.write("\t\t\t<tr >\n");
      out.write("   \t\t\t<td>");
      out.print(cnt);
      out.write(".</td>\n");
      out.write("    \t\t<td><a href= ");
      out.print(info_url );
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print(course.name);
      out.write("</a></td>\n");
      out.write("\n");
      out.write("\t\t\t");
 
			if(ans == 0)
			{
				
      out.write("<td><a href= ");
      out.print(in_url );
      out.write("> 选课 </a></td> ");

			}
			
      out.write("\n");
      out.write("\t\t\t<td>课容量:");
      out.print(course.capacity );
      out.write("</td>\n");
      out.write("\t\t\t<td>课余量:");
      out.print(chosen);
      out.write("</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t");
		
		} 
	}

      out.write("\n");
      out.write("</table>\n");
      out.write("<br/>\n");
      out.write("<font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>我已经选的课</b></p></font>\n");
      out.write("<table class=\"table table-striped\">\n");
 
	List<Integer> course_list=null;
	course_list = jdbc.getCourseIndex(user.id);
	if(course_list!=null){
		cnt = 0;
		for(Integer i : course_list)
		{ 
			Course course = jdbc.getCourse(i);
			String info_url = "course.jsp?id="+course.id+"&type=1";
			String out_url = "getout.jsp?cid="+course.id+"&uid="+user.id;
			++cnt;
			
      out.write("\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(cnt);
      out.write(". </td>\n");
      out.write("\t\t\t<td><a href= ");
      out.print(info_url );
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print(course.name);
      out.write(" </a></td>\n");
      out.write("\t\t\t<td><a href= ");
      out.print(out_url );
      out.write(" > 退课 </a></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t");

		} 
	}

      out.write("\n");
      out.write("</table>\n");
      out.write("<br/>\n");
      out.write("<font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>选课历史记录</b></p></font>\n");
      out.write("<table>\n");
      out.write("\n");
 
	List<UserCourse> history = jdbc.getUserCourseHistory(user.id);
	for(UserCourse entry:history)
	{
		
      out.write("<tr>");
 
		if(entry.operation == 1)
		{
      out.write("\n");
      out.write("\t\t<td>选课：<td/>\n");
      out.write("\t\t");
}
		else
		{
      out.write("\n");
      out.write("\t\t<td>退课:<td/>\n");
      out.write("\t\t");
}
		
      out.write("<td>课程编号   ");
      out.print(entry.course_id);
      out.write("  <td/>\n");
      out.write("\t\t<td>时间：");
      out.print(entry.time.substring(0, 19));
      out.write("  <td/>\n");
      out.write("\t\t<tr/>");
 
	}

      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
