/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 20:53:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.*;
import java.util.*;

public final class choose_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"../bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("      body {\n");
      out.write("        padding-top: 40px;\n");
      out.write("        padding-bottom: 40px;\n");
      out.write("        background-color: #f5f5f5;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .form-signin {\n");
      out.write("        max-width: 600px;\n");
      out.write("        padding: 19px 29px 29px;\n");
      out.write("        margin: 0 auto 20px;\n");
      out.write("        background-color: #fff;\n");
      out.write("        border: 1px solid #e5e5e5;\n");
      out.write("        -webkit-border-radius: 5px;\n");
      out.write("           -moz-border-radius: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("                box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("      }\n");
      out.write("      .form-signin .form-signin-heading,\n");
      out.write("      .form-signin .checkbox {\n");
      out.write("        margin-bottom: 10px;\n");
      out.write("      }\n");
      out.write("      .form-signin input[type=\"text\"],\n");
      out.write("      .form-signin input[type=\"password\"] {\n");
      out.write("        font-size: 16px;\n");
      out.write("        height: auto;\n");
      out.write("        margin-bottom: 15px;\n");
      out.write("        padding: 7px 9px;\n");
      out.write("      }\n");
      out.write("\t\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"navbar nav-pills navbar-fixed-top\">\n");
      out.write("  <div class=\"navbar-inner\">\n");
      out.write("    <a class=\"brand\" href=\"#\">INFO</a>\n");
      out.write("    <ul class=\"nav\">\n");
      out.write("      <li class=\"divider-vertical\"><a href=\"../home.jsp\">首页</a></li>\n");
      out.write("      ");
 
      	User user_tmp = (User)session.getAttribute("user");
      	if(user_tmp == null)
      	{
      		
      out.write("<li class=\"divider-vertical\" font face = \"微软雅黑\"><a href=\"../account/login.jsp\">登陆/注册</a></li> ");

      	}
      	else
      	{
      		String url = "../account/user_info.jsp?id="+user_tmp.id;
      		
      out.write("<li class=\"divider-vertical\"  font face = \"微软雅黑\"><a href=");
      out.print(url);
      out.write('>');
      out.print(user_tmp.nickname);
      out.write("</a></li> ");

      	}
      
      
      out.write("<li class=\"divider-vertical\"><a href=\"../discussion/index.jsp\">公共讨论区</a></li>");

      
      if(user_tmp != null)
      {
	      	
      out.write("<li class=\"active\"><a href=\"../courses/index.jsp\">网络学堂</a></li>\n");
      out.write("\t      \t<li class=\"divider-vertical\"><a href=\"../notice/index.jsp\">教务公告</a></li>\n");
      out.write("\t      \t<li class=\"divider-vertical\"><a href=\"../media/index.jsp\">外部资源</a></li>");

      }
 	  
      
      out.write("<li class=\"divider-vertical\"><a href=\"../intro.jsp\">师资力量</a></li>\n");
      out.write("      <li class=\"divider-vertical\"><a href=\"../author.jsp\">开发人员</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");

	JdbcDao jdbc = new JdbcDao();
	Status s = jdbc.getStatus();
	if(s.choose == 0)
	{
		
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-error\">\n");
      out.write("  \t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t <strong>Warning!</strong> 选课开关没有打开，现在不是选课时间\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 
		return;
	}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	User user = (User)session.getAttribute("user");
	if(user != null){
	
      out.write("\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("  \t<div class=\"row-fluid\">\n");
      out.write("    <div class=\"span3\">\n");
      out.write("    <br><br>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的名字：");
      out.print(user.realname );
      out.write("<br></p></font>\n");
      out.write("\t<font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的昵称：");
      out.print(user.nickname );
      out.write("<br></p></font>\n");
      out.write("\t<font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的地址：");
      out.print(user.address );
      out.write("<br></p></font>\n");
      out.write("\t<font size = 3 face =\"微软雅黑\"><p class=\"text-success\">你的手机：");
      out.print(user.phone );
      out.write("<br></p></font>\n");
      out.write("\t\n");
 	}
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"span9\">\n");
      out.write("    \n");
      out.write("\t<br><br>\n");
      out.write("    \n");
      out.write("    <font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>所有可选课程</b></p></font>\n");
  
	List<Integer> c=null; 
	user = (User)session.getAttribute("user");
	if(user==null)
	{
		
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-error\">\n");
      out.write("  \t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t <strong>Warning!</strong> 你还没有登陆，所以没有课程可以选择\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 
		return;
	}
	else
		c = jdbc.getCourseIndex(0);
	int cnt = 0;

      out.write("\t\n");
      out.write("\t\n");
 
	if(request.getParameter("fail")!=null)
	{
		if(request.getParameter("fail").equals("left"))
		{
			
      out.write("<div class=\"alert\">\n");
      out.write("\t  \t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write("\t \t\t\t\t\t\t <strong>Warning!</strong> 没有课余量了！\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t");

		}
		else if(request.getParameter("fail").equals("time"))
		{
			
      out.write("<div class=\"alert\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write("\t\t \t<strong>Warning!</strong> 选课与已有课程冲突了！\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");

		}
	}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<table class=\"table table-striped text-center\">\n");
 
	if(c!=null){
		
      out.write("<tr><td>课程序号</td><td>课程名称</td><td>授课教师</td><td>上课时间</td><td>课容量</td><td>课余量</td><td>选课操作</td><tr>");

		
		for(Integer i : c)
		{
			Course course = jdbc.getCourse(i);
			String info_url = "course.jsp?id="+course.id+"&type=1";
			String in_url = "getin.jsp?cid="+course.id+"&uid="+user.id;
			
			int ans = jdbc.checkUserCourse(user.id, course.id);
			int left = course.capacity - jdbc.getUserCourse(course.id).size();
			++cnt;
			
      out.write("  \n");
      out.write("\t\t\t<tr align =\"center\">\n");
      out.write("\t\t\t<td>");
      out.print(cnt);
      out.write(".</td>\n");
      out.write("    \t\t<td><a href= ");
      out.print(info_url );
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print(course.name);
      out.write("</a></td><td>");
      out.print(course.teacher );
      out.write("</td>\n");
      out.write("    \t\t<td>");
      out.print(course.classtime);
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(course.capacity );
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(left);
      out.write("</td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
	
			
			if(ans == 0 && left > 0)
			{
				
      out.write("<td><a href= ");
      out.print(in_url );
      out.write("> 选课 </a></td> ");

			}
			else if(left==0)
			{
				
      out.write("<td>无课余量</td> ");

			}
			else
			{
				
      out.write("<td>&nbsp</td> ");

			}
			
			
      out.write("</tr>");

		} 
	}

      out.write("\n");
      out.write("</table>\n");
      out.write("<br/>\n");
      out.write("\n");
      out.write("<font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>我的课程</b></p></font>\n");
      out.write("<table class=\"table table-striped\" >\n");
 
	int [][]map = new int[10][10];
	
      out.write("<tr><td>序号</td><td>课程名称</td><td>授课老师</td><td>上课时间</td><td>退课操作</td></tr>");
 
	List<Integer> course_list=null;
	course_list = jdbc.getCourseIndex(user.id);
	if(course_list!=null){
		cnt = 0;
		for(Integer i : course_list)
		{ 
			Course course = jdbc.getCourse(i);
			String info_url = "course.jsp?id="+course.id+"&type=1";
			String out_url = "getout.jsp?cid="+course.id+"&uid="+user.id;
			++cnt;
			
			int time = Integer.parseInt(course.classtime);
			map[time/10][time%10] = course.id;//time from 11-77
			
			
      out.write("\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(cnt);
      out.write("</td>\n");
      out.write("\t\t\t<td><a href= ");
      out.print(info_url );
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print(course.name);
      out.write(" </a></td>\n");
      out.write("\t\t\t<td>");
      out.print(course.teacher);
      out.write("</td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td>");
      out.print(course.classtime );
      out.write("</td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td><a href= ");
      out.print(out_url);
      out.write(" >退课 </a></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t");

		} 
	}

      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("<font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>我的课表</b></p></font>\n");
      out.write("<table class=\"table table-striped\" style=\"font-family:微软雅黑\">\n");
 
	String a ="一二三四五六七八";
	for(int i = 0;i != 7; i++)
	{
		
      out.write("<tr>");
 
		for(int j = 0; j != 8; j++)
		{
			String tmp = null;
			Course course = null;
			if(i + j == 0)
				tmp = "";
			else if(j == 0)
				tmp = "第"+a.charAt(i-1)+"大节";
			else if(i == 0)
				tmp = "星期"+a.charAt(j-1);	 
			else if( map[j][i] > 0)// 7 6
			{
				course = jdbc.getCourse(map[j][i]);
				tmp = course.name;
			}
			else
				tmp="";
			
      out.write("<td>");
      out.print(tmp);
      out.write("</td>");

		}	
		
      out.write("</tr>");

	}
	

      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("<br/>\n");
      out.write("<font size = 5 face =\"微软雅黑\"><p class=\"text-info\"><b>选课历史记录</b></p></font>\n");
      out.write("\n");
      out.write("<table class=\"table table-striped\">\n");
 
	List<UserCourse> history = jdbc.getUserCourseHistory(user.id);
	
      out.write("<tr><td>操作</td> <td>课程名称 </td> <td>时间</td> </tr>");
 
	
	for(UserCourse entry:history)
	{
		
      out.write("<tr>");

		Course course= jdbc.getCourse(entry.course_id);
		if(entry.operation == 1)
		{
      out.write("\n");
      out.write("\t\t<td><font color=\"green\">选课</font></td>\n");
      out.write("\t\t");
}
		else
		{
      out.write("\n");
      out.write("\t\t<td><font color=\"red\">退课</font></td>\n");
      out.write("\t\t");
}
		
		
      out.write("<td> ");
      out.print(course.name);
      out.write("  </td>\n");
      out.write("\t\t<td>");
      out.print(entry.time.substring(0, 19));
      out.write(" </td></tr>");
 
	}
	
	

      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
