/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 08:54:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mail.MailTest;
import edu.thu.cs.*;
import java.util.*;
import jdbc.*;

public final class register_005fnew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html land=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write(" <style type=\"text/css\">\n");
      out.write("      body {\n");
      out.write("        padding-top: 40px;\n");
      out.write("        padding-bottom: 40px;\n");
      out.write("        background-color: #f5f5f5;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .form-signin {\n");
      out.write("        max-width: 430px;\n");
      out.write("        padding: 19px 29px 29px;\n");
      out.write("        margin: 0 auto 20px;\n");
      out.write("        background-color: #fff;\n");
      out.write("        border: 1px solid #e5e5e5;\n");
      out.write("        -webkit-border-radius: 5px;\n");
      out.write("           -moz-border-radius: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("                box-shadow: 0 1px 2px rgba(0,0,0,.05);\n");
      out.write("      }\n");
      out.write("      .form-signin .form-signin-heading,\n");
      out.write("      .form-signin .checkbox {\n");
      out.write("        margin-bottom: 10px;\n");
      out.write("      }\n");
      out.write("      .form-signin input[type=\"text\"],\n");
      out.write("      .form-signin input[type=\"password\"] {\n");
      out.write("        font-size: 16px;\n");
      out.write("        height: auto;\n");
      out.write("        margin-bottom: 15px;\n");
      out.write("        padding: 7px 9px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("    <link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container form-signin\">\n");
      out.write("<div class=\"row-fluid\">\n");
      out.write("\n");
      out.write(" \n");
      out.write(" <form name=\"注册\"action=\"register.jsp\" method=\"post\">\n");
      out.write("\t<h1 class=\"text-center text-warning \">注册界面</h1>\n");
      out.write("\t\n");
      out.write("\t<table class=\"table table-striped\">\n");
      out.write("\t<tr>\n");
      out.write("\t<td><strong>用户名: </strong></td> \t\n");
      out.write("\t<td><input type=\"text\"  name=\"account\" />*</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr><td><strong>密码: </strong></td> \n");
      out.write("\t<td><input type=\"text\" name=\"password\"  />*</td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t</table>\n");
      out.write("</form>\t\n");
      out.write("\t\n");
      out.write("\t<br/>\n");
      out.write("\t<strong>真实姓名: </strong> \n");
      out.write("\t<input type=\"text\" name=\"realname\"  />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong>昵称: </strong> \n");
      out.write("\t<input type=\"text\" name=\"nickname\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong>性别: </strong> \t\n");
      out.write("\t<input type=\"text\" name=\"sex\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong>生日: \t</strong> \n");
      out.write("\t<input type=\"text\" name=\"birth\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong> 电话号码: </strong> \t\n");
      out.write("\t<input type=\"text\" name=\"phone\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong> 紧急联系人名字: </strong> \t\n");
      out.write("\t<input type=\"text\" name=\"e_name\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong> 紧急联系人手机号: </strong> \t\n");
      out.write("\t<input type=\"text\" name=\"e_phone\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong> 家庭住址:</strong> \n");
      out.write("\t<input type=\"text\" name=\"address\" />*\n");
      out.write("\t<br />\n");
      out.write("\t<strong> QQ号码</strong> \n");
      out.write("\t<input type=\"text\" name=\"qq\"/>\n");
      out.write("\t<br />\n");
      out.write("\n");
      out.write("\t<input type=\"submit\" class=\"btn btn-primary text-left\" value=\"confirm\" name = \"yes\" />\n");
      out.write("\t</form>\n");
      out.write("      ");

      try {
			if(request.getParameter("yes") != null) 
			{
				JdbcDao jdbc = new JdbcDao();
				User new_u = new User();
				new_u.account = request.getParameter("account");
				new_u.password = request.getParameter("password");
				new_u.realname = request.getParameter("realname");
				new_u.nickname = request.getParameter("nickname");
				new_u.sex = request.getParameter("sex");
				new_u.birth = request.getParameter("birth");
				new_u.phone = request.getParameter("phone");
				new_u.e_name = request.getParameter("e_name");
				new_u.e_phone = request.getParameter("e_phone");
				new_u.address = request.getParameter("address");
				new_u.qq = request.getParameter("qq");
				new_u.verify = 0;
				new_u.permit_login = 1;
				new_u.permit_post = 1;
				new_u.permit_admin = 0;
				if(request.getParameter("yes")!=null){
					if(new_u.account == null||new_u.password == null
					   ||new_u.realname == null||new_u.nickname == null
					   ||new_u.sex == null||new_u.birth == null
					   ||new_u.phone == null||new_u.e_name == null
					   ||new_u.e_phone == null||new_u.address == null
					   ||new_u.account == ""||new_u.password == ""
					   ||new_u.realname == ""||new_u.nickname == ""
					   ||new_u.sex == ""||new_u.birth == ""
					   ||new_u.phone == ""||new_u.e_name == ""
					   ||new_u.e_phone == ""||new_u.address == "")
					{
						
      out.write("<div class=\"alert\">\n");
      out.write("  \t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t\t\t\t\t <strong>Warning!</strong> 请勿漏填必填信息\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t");

					}
					else{
						MailTest.sendmail("xiexh_thu@163.com","http://localhost:8080/Test/success.jsp?"+"account="+new_u.account+"&num=1231023901293019");
						jdbc.addUser(new_u);
						
      out.write("<div class=\"alert alert-success\">\n");
      out.write("  \t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write(" \t\t\t\t\t\t <strong>Success!</strong> 请登录邮箱进行验证\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t");

					}
				}
			}
		} catch (Exception e) {
			System.out.println(e);
		}
	
      out.write("\n");
      out.write("<hr><a href=\"../home.jsp\"><h1 class=\"text-center\">返回首页</h1></a>\n");
      out.write("\n");
      out.write("    <script src=\"asset/js/google-code-prettify/prettify.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/application.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
