/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-21 22:27:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.thu.cs.*;
import jdbc.JdbcDao;

public final class user_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("      body {\r\n");
      out.write("        padding-top: 40px;\r\n");
      out.write("        padding-bottom: 40px;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin {\r\n");
      out.write("        max-width: 430px;\r\n");
      out.write("        padding: 19px 29px 29px;\r\n");
      out.write("        margin: 0 auto 20px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #e5e5e5;\r\n");
      out.write("        -webkit-border-radius: 5px;\r\n");
      out.write("           -moz-border-radius: 5px;\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("                box-shadow: 0 1px 2px rgba(0,0,0,.05);\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin .form-signin-heading,\r\n");
      out.write("      .form-signin .checkbox {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-signin input[type=\"text\"],\r\n");
      out.write("      .form-signin input[type=\"password\"] {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        padding: 7px 9px;\r\n");
      out.write("      }\r\n");
      out.write("      a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor:blue;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"navbar nav-pills navbar-fixed-top\">\r\n");
      out.write("  <div class=\"navbar-inner\">\r\n");
      out.write("    <a class=\"brand\" href=\"#\">INFO</a>\r\n");
      out.write("    <ul class=\"nav\">\r\n");
      out.write("      <li class=\"divider-vertical\"><a href=\"../home.jsp\">首页</a></li>\r\n");
      out.write("      ");
 
      	User user_tmp = (User)session.getAttribute("user");
      	if(user_tmp == null)
      	{
      		
      out.write("<li class=\"active\" font face = \"微软雅黑\"><a href=\"../account/login.jsp\">登陆/注册</a></li> ");

      	}
      	else
      	{
      		String url = "../account/user_info.jsp?id="+user_tmp.id;
      		
      out.write("<li class=\"active\"  font face = \"微软雅黑\"><a href=");
      out.print(url);
      out.write('>');
      out.print(user_tmp.nickname);
      out.write("</a></li> ");

      	}
      
      
      out.write("<li class=\"divider-vertical\"><a href=\"../discussion/index.jsp\">公共讨论区</a></li>");

      
      if(user_tmp != null)
      {
	      	
      out.write("<li class=\"divider-vertical\"><a href=\"../courses/index.jsp\">网络学堂</a></li>\r\n");
      out.write("\t      \t<li class=\"divider-vertical\"><a href=\"../notice/index.jsp\">教务公告</a></li>\r\n");
      out.write("\t      \t<li class=\"divider-vertical\"><a href=\"../media/index.jsp\">外部资源</a></li>");

      }
 	  
      
      out.write("<li class=\"divider-vertical\"><a href=\"../intro.jsp\">师资力量</a></li>\r\n");
      out.write("      <li class=\"divider-vertical\"><a href=\"../author.jsp\">开发人员</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<title>用户信息</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container form-signin\">\r\n");
      out.write("  <div class=\"row-fluid\">\r\n");
 
	String nickname  = request.getParameter("user");
	String id_string = request.getParameter("id");
	System.out.println("In user_info: nickname "+nickname);
	System.out.println("In id_string: id "+id_string);
	
	String this_url = "user_info.jsp";
	JdbcDao jdbc = new JdbcDao();
	User who = new User();
	if(nickname != null)
	{	
		who.id=0;
		who.nickname = nickname;
		who = jdbc.getUser(who);
		if(who==null)
			return;
	}
	else if(id_string != null)
	{
		who.id = Integer.parseInt(id_string);
		who = jdbc.getUser(who);
		if(who==null)
			return;
	}

      out.write("\r\n");
      out.write("\r\n");

	if(who != null){
		
      out.write("<h2 class=\"form-signin-heading text-warning\">");
      out.print(who.nickname);
      out.write("的资料</h2>");

		
      out.write("<font size = 3 face =\"微软雅黑\" color=black>\r\n");
      out.write("\t\t<b>账户：</b>");
      out.print(who.account );
      out.write("<br>\r\n");
      out.write("\t\t<b>名字：</b>");
      out.print(who.realname );
      out.write("<br>\r\n");
      out.write("\t\t<b>ID：</b>");
      out.print(who.id );
      out.write("<br>\r\n");
      out.write("\t\t<b>昵称：</b>");
      out.print(who.nickname );
      out.write("<br>\r\n");
      out.write("\t\t<b>生日：</b>");
      out.print(who.birth );
      out.write("<br>\r\n");
      out.write("\t\t<b>地址：</b>");
      out.print(who.address );
      out.write("<br>\r\n");
      out.write("\t\t<b>e_name:</b>");
      out.print(who.e_name );
      out.write("<br>\r\n");
      out.write("\t\t<b>e_phone:</b>");
      out.print(who.e_phone );
      out.write("<br>\r\n");
      out.write("\t\t<b>sex:</b>");
      out.print(who.sex );
      out.write("<br>\r\n");
      out.write("\t\t<b>qq:</b> ");
 if(who.qq!=null&&!who.qq.equals("")){out.println(who.qq);}
      out.write("<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<b>登陆权限:</b>");
      out.print(who.permit_login );
      out.write("<br>\r\n");
      out.write("\t\t<b>发帖权限:</b>");
      out.print(who.permit_post );
      out.write("<br>\r\n");
      out.write("\t\t<b>管理员权限:</b>");
      out.print(who.permit_admin );
      out.write("<br>\r\n");
      out.write("\t\t");

		User user = (User)session.getAttribute("user");
		if(user != null)
		{
			user = jdbc.getUser(user);
			session.setAttribute("user", user);
			
			if(user.id == who.id)
			{
				
      out.write("<a href = \"modify.jsp\"><b>修改个人资料</b></a>");

			}
			else if(user.permit_admin > 0)
			{
				String not_login = this_url+"?id="+who.id+"&action=not_login";
				String yes_login = this_url+"?id="+who.id+"&action=yes_login";
				String not_post = this_url+"?id="+who.id+"&action=not_post";
				String yes_post = this_url+"?id="+who.id+"&action=yes_post";
				String not_admin = this_url+"?id="+who.id+"&action=not_admin";
				String yes_admin = this_url+"?id="+who.id+"&action=yes_admin";	
				
      out.write("<h4>管理员可以修改他人权限</h4>\r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(not_login);
      out.write(">禁止登陆</a>  \r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(yes_login);
      out.write(">恢复登陆</a><br>\r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(not_post );
      out.write(">禁止发帖 </a>\r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(yes_post );
      out.write(">恢复发帖</a><br>\r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(yes_admin );
      out.write(">升级为管理员 </a>\r\n");
      out.write("\t\t\t\t<a href = ");
      out.print(not_admin );
      out.write(">取消管理员 </a>");

				
				String action = null;
				action = request.getParameter("action");
				if(action != null)
				{
					User user_ = new User(); 
					user_.id = Integer.parseInt(request.getParameter("id"));
					System.out.println(user_.id);
					user_ = jdbc.getUser(user_);
					if(action.equals("not_login"))
						user_.permit_login = 0;
					else if(action.equals("yes_login"))
						user_.permit_login = 1;
					else if(action.equals("not_post"))
						user_.permit_post = 0;
					else if(action.equals("yes_post"))
						user_.permit_post = 1;
					else if(action.equals("yes_admin"))
						user_.permit_admin = 1;
					else if(action.equals("not_admin"))
						user_.permit_admin = 0;
					jdbc.updateUser(user_);
					
					if(nickname != null)
						response.sendRedirect(this_url+"?user="+nickname);
					else
						response.sendRedirect(this_url+"?id="+who.id);
				}	
			}
		}
	}

      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<button class=\"btn btn-primary\" ><a href=\"../home.jsp\" style=\"color:white\">返回首页</a></button>\r\n");
      out.write("\r\n");
 
	User user_now = (User)session.getAttribute("user");
	if(user_now != null && user_now.id==who.id)
	{	
		
      out.write("<button class=\"btn btn-success\" ><a href=\"../home.jsp?quit=yes\" style=\"color:white\">注销登陆</a></button>");

		
		String change_url = this_url+"?action=1&id="+who.id;
		String remain_url = this_url+"?id="+who.id;
		
		
      out.write("<button class=\"btn btn-primary\" ><a href=");
      out.print(change_url);
      out.write(" style=\"color:white\">修改密码</a></button>");

		
		if(request.getParameter("action")!= null)
		{
			
      out.write("<br><br>\r\n");
      out.write("\t\t\t<form action=");
      out.print(remain_url );
      out.write(" method=\"post\">\r\n");
      out.write("\t\t\t<p class=\"form-signin-heading text-warning \" ><font size =3>请输入你的新密码：</p>\r\n");
      out.write("\t\t\t<input type = \"password\" class=\"span6 input-block-level\" name = \"password\"/> \r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"btn btn-large btn-info\" name = \"regain\" value=\"确认\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");

		}
		else if(request.getParameter("regain")!=null)
		{
			String password = request.getParameter("password"); 
			user_now.password = password;
			jdbc.updateUser(user_now);
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"alert alert=success\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("\t\t\t\t你好!<strong> ");
      out.print(user_now.realname);
      out.write(" </strong>密码修改成功!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 
			session.setAttribute("user", user_now);
		}

	}

	if(user_now != null && user_now.id==who.id && user_now.permit_admin > 0)
	{	
		
      out.write("<button class=\"btn btn-danger\" ><a href=\"../admin/index.jsp\" style=\"color:white\">管理员界面</a></button>");

	}

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
