/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2014-09-11 15:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class learn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 private int count = 0; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>This is a learning page</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 以下特效CSS */\r\n");
      out.write("body {font-size:12px;}\r\n");
      out.write("ul,li {list-style:none; margin:0px; padding:0px;}\r\n");
      out.write("img {border:0;}\r\n");
      out.write("#n{margin:10px auto; width:920px; border:1px solid #CCC;font-size:12px; line-height:30px;}\r\n");
      out.write("#n a{ padding:0 4px; color:#333}\r\n");
      out.write(".focus {width:600px; height:280px; margin:0 auto; overflow:hidden; position:relative;}\r\n");
      out.write(".focus ul {height:380px; position:absolute;}\r\n");
      out.write(".focus ul li {float:left; width:600px; height:280px; overflow:hidden; position:relative; background:#000;}\r\n");
      out.write(".focus ul li div {position:absolute; overflow:hidden;}\r\n");
      out.write(".focus .btnBg {position:absolute; width:600px; height:20px; left:0; bottom:0; background:#000; display:none;}\r\n");
      out.write(".focus .btn {position:absolute; width:580px; height:23px; padding:0px 10px 0px 10px; right:0; bottom:6px; text-align:right;}\r\n");
      out.write(".focus .btn span {display:inline-block; _display:inline; _zoom:1; width:25px; height:24px; line-height:24px; text-align:center; _font-size:0; margin-left:5px; cursor:pointer; background:#fff;}\r\n");
      out.write(".focus .btn span.on {background:#fff;}\r\n");
      out.write(".focus .preNext {width:45px; height:100px; position:absolute; top:90px; background:url(img/sprite.png) no-repeat 0 0; cursor:pointer;}\r\n");
      out.write(".focus .pre {left:0;}\r\n");
      out.write(".focus .next {right:0; background-position:right top;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/sl.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t  \t$.focus(\"#focus001\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor= \"#8080C0\">\r\n");
      out.write("<h1 align =\"center\"><font size = 8 face =\"微软雅黑\" >This is Tribble shit's big homework</font></h1>\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("Account:<input type=\"text\" name=\"account\">Password:<input type=\"password\" name=\"password\">\r\n");
      out.write("<em>Are you an idiot?</em>\r\n");
      out.write("<input type=\"radio\" name=\"sex\" value=\"Yes\">Yes\r\n");
      out.write("<input type=\"radio\" name=\"sex\" value=\"No\">No\r\n");
      out.write("<input type=\"submit\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<hr><div class=\"focus\" id=\"focus001\" align=\"left\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"http://www.divcss5.com/\" target=\"_blank\"><img src=\"img/01.jpg\" alt=\"jquery特效\" /></a></li>\r\n");
      out.write("        <li><a href=\"http://www.divcss5.com/\" target=\"_blank\"><img src=\"img/02.jpg\" alt=\"DIVCSS5\" /></a></li>\r\n");
      out.write("        <li><a href=\"#\" target=\"_blank\"><img src=\"img/03.jpg\" alt=\"点击左右滚动jquery焦点图特效\" /></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<blockquote>\r\n");
      out.write("<p>Access to this page since server reboot: ");
      out.print( ++count );
      out.write(" --God</p> \r\n");
      out.write("These two guys are genius! --Dashit\r\n");
      out.write("</blockquote>\r\n");
      out.write("<a href=\"http://www.baidu.com\"><img border= \"0\" src = \"img/Bolt.jpg\"  height = \"300\"></a>\r\n");
      out.write("<a href=\"http://www.sina.com.cn\"><img border= \"0\" src = \"img/Double.jpg\"  height = \"300\"></a><br>\r\n");
      out.write("<a href=\"hbisheng@126.com?subject=Hello%20again\">Send mail</a>\r\n");
      out.write("\r\n");
      out.write("<hr><table border=\"7\" cellpadding = \"10\" background = \"img/silk_texture.jpg\">\r\n");
      out.write("<caption>Here is our time table</caption>\r\n");
      out.write("<tr align =\"center\"><th>Day1</th><th>Day2</th><th>Day3</th><th>Day4</th><th>Day5</th><th>Day6</th><th>Day7</th></tr>\r\n");
      out.write("<tr align =\"center\"><td>9.12</td><td>9.13</td><td>9.14</td><td>9.15</td><td>9.16</td><td>9.17</td><td>9.18</td></tr>\r\n");
      out.write("<tr align =\"center\"><td>Fucking play</td><td>Fucking play</td><td>Fucking play</td><td>Fucking play</td><td>Work!</td><td>Work!</td><td>Work!</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div bgcolor=\"red\">\r\n");
      out.write("<h3>To do list</h3>\r\n");
      out.write("\r\n");
      out.write("<ul type = \"square\"><li>Breakfast is on you.\r\n");
      out.write("<li>Lunch is on qin.\r\n");
      out.write("<li>Dinner is on me.\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr><p>Making a new Info is our goal!!!</p>\r\n");
      out.write("<a href=\"http://info.tsinghua.edu.cn\" target=\"_blank\" name = \"label\">Click here to see!</a>\r\n");
      out.write("<font color = \"#02DF82\" size = 4>\r\n");
      out.write("<p>Donate to support us</p>\r\n");
      out.write("100084<br>\r\n");
      out.write("Tsinghua University<br>\r\n");
      out.write("Zijing No.2 building<br>\r\n");
      out.write("109A<br>\r\n");
      out.write("</font>\r\n");
      out.write("\t");
 for (int i = 0; i < 10; i++){ 
      out.write("\r\n");
      out.write("\t\tA loop\r\n");
      out.write("\t");
 }
      out.write("\r\n");
      out.write("\t<p>An expression: ");
      out.print( Integer.toString(2*3*4*5) );
      out.write("</p>\r\n");
      out.write("\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${7/3.0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<font color=\"#FF0000\"><b>Red!!</b></font> \r\n");
      out.write("\t<del>delete this para</del>\r\n");
      out.write("\t<ins>insert a sentense</ins>\r\n");
      out.write("<hr>\r\n");
      out.write(" \r\n");
      out.write("<p>Any recommendation?</p>\r\n");
      out.write("<textarea rows=\"20\" cols=\"100\">This is fucking good!</textarea>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
